# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(e6c6066c-121b-4225-b65c-42ee806a9be4)'
    appType: 'webApp'
    WebAppName: 'devappsvc'
    deployToSlotOrASE: true
    ResourceGroupName: 'demo-rg'
    SlotName: 'dev'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'


