# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '*.csproj'
  displayName: 'Build project'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
  displayName: 'Publish'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(e6c6066c-121b-4225-b65c-42ee806a9be4)'
    appType: 'webApp'
    WebAppName: 'devappsvc'
    deployToSlotOrASE: true
    ResourceGroupName: 'demo-rg'
    SlotName: 'dev'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
  displayName: 'Deploy to Dev slot'

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Pay-As-You-Go(e6c6066c-121b-4225-b65c-42ee806a9be4)'
    Action: 'Swap Slots'
    WebAppName: 'devappsvc'
    ResourceGroupName: 'demo-rg'
    SourceSlot: 'dev'
  displayName: 'Swap slots'
  
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'client'
  displayName: 'Run npm install'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'client'
    customCommand: 'run build'
  displayName: 'Build React client'


